### ISSUE TITLE
2-axis solar tracking issues

### ISSUE THREAD

**Issue by Evanion** [dtandersen/stationeers-library#1]
I have built this circuit twice now, and each time it fails...
The panels park to the east in the evening in anticipation for sunrise.. but when the sun rises, the panels start rotating virtically in the opposite direction of the suns movement, and it's not tracking the sun inverted, the panels are moving as fast as they can .. and when they reach the max movement, they instantly flip 180, and continue moving.
* Solar panels powerports are facing east (sunrise) (and network ports face west)
* Solar sensors powerports face south
* 1xIC housing
* 2x memory
* 2x batch writers

I don't know what I'm doing wrong ...

**Comment by dtandersen** [comment]
The code is too old to work at this point.
